### ISSUE TITLE
Implement support for "Poetry" for website.

### ISSUE THREAD

**Issue by thomasmansencal** [colour-science/colour-science.org#3]
The website is currently using `nikola` and `nikola[extras]`. We should setup [Poetry](https://poetry.eustace.io/) for it like we did for [Colour](https://github.com/colour-science/colour/blob/develop/pyproject.toml) so that it is easier to get working on it.

**Comment by evalevanto** [comment]
I'd like to take this up.

**Comment by thomasmansencal** [comment]
Hi @evalevanto,

Thanks that would be great! There might be some details missing in the description but I think that should be it overall!

Let me know if any issues, as I think you are one the first person trying to build our website :)

**Comment by evalevanto** [comment]
Generated a pyproject.toml file which will serve as main dependency manager for any python code added into the site. 
More clarification on what more is required of this issue

**Comment by evalevanto** [comment]
Let me submit a PR then get comments regarding it
