### ISSUE TITLE
Describe how to use "Poetry" to get running with "Colour".

### ISSUE THREAD

**Issue by thomasmansencal** [colour-science/colour-science.org#4]
We should update the installation guide to showcase how to use  [Poetry](https://poetry.eustace.io/) to get running with [Colour](https://github.com/colour-science/colour/).

**Comment by AlexandruBuhai** [comment]
I would like to work on this.

**Comment by thomasmansencal** [comment]
Awesome @AlexandruBuhai :)

**Comment by AlexandruBuhai** [comment]
I've been hammered at work and can't work on this, so if you can, un-claim me from the list to give a chance to others. I will still try it next week if no one claimed before that. Thanks and sorry!

**Comment by thomasmansencal** [comment]
No worries and good luck with work!

**Comment by thomasmansencal** [comment]
I thought I closed another PR, time for some sleep here too :)

**Comment by thomasmansencal** [comment]
I have actually done it!
